#+title: Notitzen

> Bemerkung: ~.org~-Dateien werden von GitHub manchmal nicht korrekt angezeigt.

**** Konventionen für die Benennung in der Bibliothek:

Da Englisch die "lingua franca" der Softwareentwicklung ist, meide ich es normalerweise, deutsche Bezeichnungen zu nutzen. Jedoch ergibt sich hier ein Problem, da WILLI2 ein ausschließlich deutsches Programm ist, weshalb das Übersetzen der Spaltennamen ins Englische mehr Verwirrung zu verursachen scheint, als es behebt. Als Mittelweg habe ich deshalb entschieden, Spaltennamen wörtlich zu übernehmen, für die repräsentativen Datenstrukturen (e.g. ~WilliDocument~, ~WilliPeriod~, etc.) aber englische Namen einzusetzen.


* Das "BAL"-Format

Willi speichert seine Stundenpläne in Dateien mit der Endung ~.BAL~. Das Format scheint für den Internen gebrauch und nicht dokumentiert zu sein.

BAL-Dateien sind grundsätzlich CSV-dateien. Sie beginnen jedoch mit folgender Kopfzeile:

#+begin_example
---------- WILLI2-Stundenplan ---------- Version: 430 ----------
#+end_example

Spaltenbezeichnungen fehlen komplett. Nach der Kopfzeile besteht das Dokument nur noch aus CSV-Zeilen — jedoch nicht mit einheitlicher Länge; es handelt sich also um mehrere unabhängige Tabellen. Diese erste Spalte scheint der Unterscheidung zu dienen. Sie besteht aus einer Abfolge von bis zu drei Buchstaben, manchmal gefolgt von Ziffern, die einen Primärschlüssel darzustellen scheinen. Es erscheinen in den vorgelegten Dateien folgende solche "typen" (in Reihenfolge):

- [ ] ~W~ — Nur eine Zeile, scheint die Schule zu identifizieren
- [ ] ~WP~ — Zweck unbekannt
- [x] ~T{x}~ — Tage des Stundenplans, siehe [[T-Zeilen]]
- [x] ~S{x}~ — [[S-Zeilen][Stunden des Plans]]
- [ ] ~MP~ — Zweck unbekannt; scheint der Zahl der Stunden zu entsprechen
- [-] ~L{x}~ — Lehrer
  Teilweise implementiert; Einige der Felder sind noch nicht bekannt
- [ ] ~LB{x}~ — Zweck unbekannt
  Diese Tabelle ordnet einigen Lehrerkürzeln jeweils eine unterschiedlich Lange, musterlose Kette von Kleinbuchstaben zu. Interessanterweise ist der Index ~{x}~ nicht unbedingt Aufeinanderfolgend, sondern entspricht dem jeweiligen Index des Lehrers in ~L{x}~.
- [ ] ~R{x}~ — Räume
- [ ] ~G{x}~ — Zweck unbekannt
- [ ] ~F{x}~ — Fächer
- [ ] ~K{x}~ — Klassen
- [ ] ~X{x}~ — Zweck unbekannt; möglicherweise Sonderereignisse
- [ ] ~O{x}~ — Zweck unbekannt; möglicherweise Gebiete für Pausenaufsicht
- [ ] ~Z{x}~ — Zweck unbekannt
- [ ] ~A{x}~ — Zweck unbekannt; scheinbar Zugeordnet zu ~O{x}~. Möglicherweise zuordnungen der Pausenaufsicht?
- [ ] ~AV{x}~ — Zweck unbekannt; enthält nur Nullen.
- [ ] ~J{x}~ — Zweck unbekannt; Jede Zeile enthält ein Fach, eine Leerspalte und die Zahl ~"12632256"~
- [ ] ~U{x}~ — Zuordnung der Unterrichtsstunden
- [ ] ~PL[S]~ — Zweck unbekannt

  Die Typspalte dieser Tabelle enthält keinen Index, dafür aber manchmal den Buchstaben ~S~ nach ~PL~. Zeilen beginnend mit ~PL~ und ~PLS~ sind vermischt.
- [ ] ~PKS~ — Zweck unbekannt
- [ ] ~PRS~ — Zweck unbekannt

Markierte Elemente sind Tabellentypen, deren Verarbeitung bereits in der Bibliothek umgesetzt ist.

** T-Zeilen

Die Tabelle ~T{x}~ entsprechen offensichtlich dem [[https://willi.wgg-neumarkt.de/handbuch/willi/willi.html][Stundenraster]]. Sie ordnet jedem Tag eine Kurzbezeichnung, eine Langbezeichnung und zwei weitere Zeichenketten zu, die jeweils den Stunden und Pausen des Tages entsprechen.

#+begin_example
     Kurzname,Langname,Stundenarten              ,Pausen
"T1","Mo"    ,"Montag","VVVVVVnNNNNXXXXXXXXXXXXX","...P...................."
#+end_example

Die Stundentypen "V" (Vormittagsstunde), "N" (Nachmittagsstunde), "M" (Mittagspause) und "MN" (Mittagspause/Nachmittagsstunde) sind im Handbuch dokumentiert. Da jeder Stunde nur ein Zeichen zusteht, wird "MN" offenbar vom kleingeschriebenen "n" repräsentiert.

** S-Zeilen

Die Tabelle ~S{x}~ ordnet jeder Stundennummer ein entsprechendes Zeitfenster zu. Das Handbuch spricht von bis zu 5 möglichen alternativen Zeitrastern; da in dem mir vorliegenden Stundenplan keine solchen vorhanden sind kann ich aber nicht darauf schließen, wie diese in der Stundenplandatei repräsentiert werden. S-Zeilen scheinen aber für das Hauptzeitraster vorbehalten zu sein.

#+begin_example
"S1","1","8.00-8.45","8:00","8:45"
#+end_example

Interessanterweise scheint die Zeile eine dopplung zu enthalten: Die letzten beiden Spalten beschreiben jeweils start und ende der Stunde; die dritte Spalte beide Zusammen. Doch dem ist nicht ganz so — in meiner Stundenplandatei stimmen die Zeilen zu begin überein, weichen aber ab der 6. Stunde ab:

#+begin_example
"S6","6","12.15-13.00","12:30","13:15"
#+end_example

Die angaben in der kombinierten Spalte sind korrekt; die anderen beiden weichen aus mir unklaren Gründen ab. Ein öffnen der Datei in WILLI offenbart, dass die letzten beiden Spalten tatsächlich "Beginn" und "Ende" sind, die andere eine "Langbezeichnung". Es scheint also, dass die Schule zwecks Drucken die Langbezeichnungen manuell eingegeben und aktuell gehalten hat, die anderen aber, da sie vermutlich nicht im Ausdruck erscheinen einfach nie aktualisiert. Can't have shit in detroit.

** L-Zeilen

Viele der Spalten der ~L~-Zeilen erscheinen im Programm in anderer Reihenfolge als in der Tabelle und andere erscheinen überhaupt nicht in der WILLI-Ansicht. Deshalb werden momentan nur einige der Felder von der Bibliothek erkannt.

#+begin_example
        Kürzel,Kurzname,Name           ,Vorname,Andrede,                                        SollWs, Fkt.,Lück?,        Block,Vert,-Früh,-Spät,HzHohl,AufsMax,BewNm,    StdMx,VerfMx,                 NachmMx,
"L41",  "KUR" ,"KUR"   ,"Kurz Kristina",       ,       ,"4,000","0,000","0,000","0,000","0,000","4"   ,,"D" ,"3"  ,"0","0","1"  ,"0" ,"0"  ,"0"  ,"5"   ,"3"    ,"N"  ,,,,,"6"  ,"2"   ,,"0,000","0,000","3"    ,,"0,000","0,000"
#+end_example
