#+title: Notitzen

> Bemerkung: ~.org~-Dateien werden von GitHub manchmal nicht korrekt angezeigt.

* Das "BAL"-Format

Willi speichert seine Stundenpläne in Dateien mit der Endung ~.BAL~. Das Format scheint für den Internen gebrauch und nicht dokumentiert zu sein.

BAL-Dateien sind grundsätzlich CSV-dateien. Sie beginnen jedoch mit folgender Kopfzeile:

#+begin_example
---------- WILLI2-Stundenplan ---------- Version: 430 ----------
#+end_example

Spaltenbezeichnungen fehlen komplett. Nach der Kopfzeile besteht das Dokument nur noch aus CSV-Zeilen — jedoch nicht mit einheitlicher Länge; es handelt sich also um mehrere unabhängige Tabellen. Diese erste Spalte scheint der Unterscheidung zu dienen. Sie besteht aus einer Abfolge von bis zu drei Buchstaben, manchmal gefolgt von Ziffern, die einen Primärschlüssel darzustellen scheinen. Es erscheinen in den vorgelegten Dateien folgende solche "typen" (in Reihenfolge):

- [ ] ~W~ — Nur eine Zeile, scheint die Schule zu identifizieren
- [ ] ~WP~ — Zweck unbekannt
- [ ] ~T{x}~ — Tage des Stundenplans, siehe [[T-Zeilen]]
- [ ] ~S{x}~ — [[S-Zeilen][Stunden des Plans]]
- [ ] ~MP~ — Zweck unbekannt; scheint der Zahl der Stunden zu entsprechen
- [ ] ~L{x}~ — Lehrer
- [ ] ~LB{x}~ — Zweck unbekannt

  Diese Tabelle ordnet einigen Lehrerkürzeln jeweils eine unterschiedlich Lange, musterlose Kette von Kleinbuchstaben zu. Interessanterweise ist der Index ~{x}~ nicht unbedingt Aufeinanderfolgend, sondern entspricht dem jeweiligen Index des Lehrers in ~L{x}~.

- [ ] ~R{x}~ — Räume
- [ ] ~G{x}~ — Zweck unbekannt
- [ ] ~F{x}~ — Fächer
- [ ] ~K{x}~ — Klassen
- [ ] ~X{x}~ — Zweck unbekannt; möglicherweise Sonderereignisse
- [ ] ~O{x}~ — Zweck unbekannt; möglicherweise Gebiete für Pausenaufsicht
- [ ] ~Z{x}~ — Zweck unbekannt
- [ ] ~A{x}~ — Zweck unbekannt; scheinbar Zugeordnet zu ~O{x}~. Möglicherweise zuordnungen der Pausenaufsicht?
- [ ] ~AV{x}~ — Zweck unbekannt; enthält nur Nullen.
- [ ] ~J{x}~ — Zweck unbekannt; Jede Zeile enthält ein Fach, eine Leerspalte und die Zahl ~"12632256"~
- [ ] ~U{x}~ — Zuordnung der Unterrichtsstunden
- [ ] ~PL[S]~ — Zweck unbekannt

  Die Typspalte dieser Tabelle enthält keinen Index, dafür aber manchmal den Buchstaben ~S~ nach ~PL~. Zeilen beginnend mit ~PL~ und ~PLS~ sind vermischt.
- [ ] ~PKS~ — Zweck unbekannt
- [ ] ~PRS~ — Zweck unbekannt

Markierte Elemente sind Tabellentypen, deren Verarbeitung bereits in der Bibliothek umgesetzt ist.

** T-Zeilen

Die Tabelle ~T{x}~ entsprechen offensichtlich dem [[https://willi.wgg-neumarkt.de/handbuch/willi/willi.html][Stundenraster]]. Sie ordnet jedem Tag eine Kurzbezeichnung, eine Langbezeichnung und zwei weitere Zeichenketten zu, die jeweils den Stunden und Pausen des Tages entsprechen.

#+begin_example
"T1","Mo","Montag","VVVVVVnNNNNXXXXXXXXXXXXX","...P...................."
#+end_example

Die Stundentypen "V" (Vormittagsstunde), "N" (Nachmittagsstunde) und "M" (Mittagspause) sind im Handbuch dokumentiert. Da hier "n" für die Mittagspause steht, gehe ich vorerst davon aus, dass "n" auch als "M" aufzufassen ist.

:NOTE:
Es wird im Handbuch auch ohne weitere Erklärung die Stunde "MN" verwendet, vermutlich um Mittagspausen zu designieren, die auch manchmal Nachmittagsstunden sind. Möglicherweise ist "n" also das Symbol für "MN"-Stunden.
:END:

** S-Zeilen

Die Tabelle ~S{x}~ ordnet jeder Stundennummer ein entsprechendes Zeitfenster zu. Das Handbuch spricht von bis zu 5 möglichen alternativen Zeitrastern; da in dem mir vorliegenden Stundenplan keine solchen vorhanden sind kann ich aber nicht darauf schließen, wie diese in der Stundenplandatei repräsentiert werden. S-Zeilen scheinen aber für das Hauptzeitraster vorbehalten zu sein.

#+begin_example
"S1","1","8.00-8.45","8:00","8:45"
#+end_example

Interessanterweise scheint die Zeile eine dopplung zu enthalten: Die letzten beiden Spalten beschreiben jeweils start und ende der Stunde; die dritte Spalte beide Zusammen. Doch dem ist nicht ganz so — in meiner Stundenplandatei stimmen die Zeilen zu begin überein, weichen aber ab der 6. Stunde ab:

#+begin_example
"S6","6","12.15-13.00","12:30","13:15"
#+end_example

Die angaben in der kombinierten Spalte sind korrekt; die anderen beiden weichen aus mir unklaren Gründen ab. Deshalb errechnet die Bibliothek aktuell Stundenbegin- und Ende aus der Kombispalte und ignoriert die anderen beiden.
