[package]
name = "willi"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
wasm-bindgen = "0.2"

[lib]
crate-type = ["cdylib"]
